apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
spec:
  type: LoadBalancer
  selector:
    app: grpc-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: allansli/grpc-client:latest
          env:
            - name: SERVER_HOST
              value: grpc-server-service.default.svc.cluster.local
            - name: LOAD_BALANCING
              value: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  labels:
    app: grpc-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: allansli/grpc-server:latest
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  clusterIP: None
  selector:
    app: grpc-server
  ports:
    - port: 50052
      targetPort: 50052